### ISSUE TITLE
Possible Incorrect CSS Link

### ISSUE THREAD

**Issue by ashfurrow** [kennethormandy/utility-opentype#3]
Hey there! Really cool project! I noticed that the `link` provided for plain CSS provided at http://utility-opentype.kennethormandy.com/#usage points to http://utility-opentype.kennethormandy.com/css/index.css but this appears to be the CSS for the site itself (it contains styles for the `body` tag, for example). Am I missing anything?

**Comment by kennethormandy** [comment]
Thanks so much! You were right, this was a placeholder I meant to fix before the launch.

I made sure the old URL still points to the master CSS file so it should actually work now for anyone who might have decided to use it, and now it points to the actual compiled CSS file on http://rawgit.com/. Thanks for pointing it out.

**Comment by ashfurrow** [comment]
Super, glad I could help :)
